// <auto-generated />
namespace CompileError.DatabaseContext.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class purchasesupplierRelationFixed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(purchasesupplierRelationFixed));
        
        string IMigrationMetadata.Id
        {
            get { return "201912040647465_purchase-supplierRelationFixed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
